const ASSET_DATA = [
    {
        imageUrl: require('../../images/hikvision1.jpeg'),
        id: '',
        cameraID: 'CRL001',
        brand: 'Hikvision',
        ipAddress: '192.168.1.101',
        model: '[Model Name]',
        type: 'Dome'
    },
    {
        imageUrl: require('../../images/hikvision2.jpeg'),
        id: '',
        cameraID: 'CRL002',
        brand: 'Hikvision',
        ipAddress: '192.168.1.102',
        model: '[Model Name]',
        type: 'Bullet',
    },
    {
        imageUrl: require('../../images/hikvision3.jpeg'),
        id: '',
        cameraID: 'CRL003',
        brand: 'Hikvision',
        ipAddress: '192.168.1.103',
        model: '[Model Name]',
        type: 'PTZ',
    },
    {
        imageUrl: require('../../images/hikvision1.jpeg'),
        id: '',
        cameraID: 'CRL004',
        brand: 'Hikvision',
        ipAddress: '192.168.1.104',
        model: '[Model Name]',
        type: 'Dome'
    },
    {
        imageUrl: require('../../images/hikvision2.jpeg'),
        id: '',
        cameraID: 'CRL005',
        brand: 'Hikvision',
        ipAddress: '192.168.1.105',
        model: '[Model Name]',
        type: 'Bullet',
    },
    {
        imageUrl: require('../../images/hikvision3.jpeg'),
        id: '',
        cameraID: 'CRL006',
        brand: 'Hikvision',
        ipAddress: '192.168.1.106',
        model: '[Model Name]',
        type: 'PTZ',
    },
    {
        imageUrl: require('../../images/hikvision1.jpeg'),
        id: '',
        cameraID: 'CRL007',
        brand: 'Hikvision',
        ipAddress: '192.168.1.101',
        model: '[Model Name]',
        type: 'Dome'
    },
    {
        imageUrl: require('../../images/hikvision2.jpeg'),
        id: '',
        cameraID: 'CRL008',
        brand: 'Hikvision',
        ipAddress: '192.168.1.102',
        model: '[Model Name]',
        type: 'Bullet',
    },
    {
        imageUrl: require('../../images/hikvision3.jpeg'),
        id: '',
        cameraID: 'CRL009',
        brand: 'Hikvision',
        ipAddress: '192.168.1.103',
        model: '[Model Name]',
        type: 'PTZ',
    },
    {
        imageUrl: require('../../images/hikvision1.jpeg'),
        id: '',
        cameraID: 'CRL010',
        brand: 'Hikvision',
        ipAddress: '192.168.1.104',
        model: '[Model Name]',
        type: 'Dome'
    },
    {
        imageUrl: require('../../images/hikvision2.jpeg'),
        id: '',
        cameraID: 'CRL011',
        brand: 'Hikvision',
        ipAddress: '192.168.1.105',
        model: '[Model Name]',
        type: 'Bullet',
    },
    {
        imageUrl: require('../../images/hikvision3.jpeg'),
        id: '',
        cameraID: 'CRL012',
        brand: 'Hikvision',
        ipAddress: '192.168.1.106',
        model: '[Model Name]',
        type: 'PTZ',
    },

]

export default ASSET_DATA;