export const CCTV_ASSET_DATA = [
    {
        imageUrl: require('../images/cctv-dome.png'),
        id: '1',
        cameraID: 'Front Door',
        brand: 'Hikvision',
        ipAddress: '192.168.1.101',
        model: '[Model Name]',
        type: 'Dome'
    },
    {
        imageUrl: require('../images/cctv-bullet.png'),
        id: '2',
        cameraID: 'Driveway',
        brand: 'Hikvision',
        ipAddress: '192.168.1.102',
        model: '[Model Name]',
        type: 'Bullet',
    },
    {
        imageUrl: require('../images/cctv-ptz.png'),
        id: '3',
        cameraID: 'Patio',
        brand: 'Hikvision',
        ipAddress: '192.168.1.103',
        model: '[Model Name]',
        type: 'PTZ',
    },
    {
        imageUrl: require('../images/cctv-dome.png'),
        id: '4',
        cameraID: 'Garage',
        brand: 'Hikvision',
        ipAddress: '192.168.1.104',
        model: '[Model Name]',
        type: 'Dome'
    },
    // {
    //     imageUrl: require('../images/cctv-bullet.png'),
    //     id: '5',
    //     cameraID: 'CRL005',
    //     brand: 'Hikvision',
    //     ipAddress: '192.168.1.105',
    //     model: '[Model Name]',
    //     type: 'Bullet',
    // },
    // {
    //     imageUrl: require('../images/cctv-ptz.png'),
    //     id: '6',
    //     cameraID: 'CRL006',
    //     brand: 'Hikvision',
    //     ipAddress: '192.168.1.106',
    //     model: '[Model Name]',
    //     type: 'PTZ',
    // },
    // {
    //     imageUrl: require('../images/cctv-dome.png'),
    //     id: '7',
    //     cameraID: 'CRL007',
    //     brand: 'Hikvision',
    //     ipAddress: '192.168.1.101',
    //     model: '[Model Name]',
    //     type: 'Dome'
    // },
    // {
    //     imageUrl: require('../images/cctv-bullet.png'),
    //     id: '8',
    //     cameraID: 'CRL008',
    //     brand: 'Hikvision',
    //     ipAddress: '192.168.1.102',
    //     model: '[Model Name]',
    //     type: 'Bullet',
    // },
    // {
    //     imageUrl: require('../images/cctv-ptz.png'),
    //     id: '9',
    //     cameraID: 'CRL009',
    //     brand: 'Hikvision',
    //     ipAddress: '192.168.1.103',
    //     model: '[Model Name]',
    //     type: 'PTZ',
    // },
    // {
    //     imageUrl: require('../images/cctv-dome.png'),
    //     id: '10',
    //     cameraID: 'CRL010',
    //     brand: 'Hikvision',
    //     ipAddress: '192.168.1.104',
    //     model: '[Model Name]',
    //     type: 'Dome'
    // },
    // {
    //     imageUrl: require('../images/cctv-bullet.png'),
    //     id: '11',
    //     cameraID: 'CRL011',
    //     brand: 'Hikvision',
    //     ipAddress: '192.168.1.105',
    //     model: '[Model Name]',
    //     type: 'Bullet',
    // },
    // {
    //     imageUrl: require('../images/cctv-ptz.png'),
    //     id: '12',
    //     cameraID: 'CRL012',
    //     brand: 'Hikvision',
    //     ipAddress: '192.168.1.106',
    //     model: '[Model Name]',
    //     type: 'PTZ',
    // },
]


export const ACCESS_ASSET_DATA = [
    {
        imageUrl: require('../images/access-door.png'),
        id: '1',
        cameraID: 'Front Door',
        brand: '[POSITION]',
        model: '[STATUS]',
        type: '[ACTION BUTTON]'
    },
    {
        imageUrl: require('../images/access-door.png'),
        id: '2',
        cameraID: 'Side Door',
        brand: '[POSITION]',
        ipAddress: '192.168.1.102',
        model: '[STATUS]',
        type: '[ACTION BUTTON]',
    },
    {
        imageUrl: require('../images/access-door.png'),
        id: '3',
        cameraID: 'Rear Door',
        brand: '[POSITION]',
        model: '[STATUS]',
        type: '[ACTION BUTTON]',
    },
]
